name: Tumblr Auto Poster

on:
  workflow_dispatch:  # Manually run from GitHub
  schedule:
    - cron: "0 8 * * *"  # Runs daily at 8:00 UTC (10:00 Italy time)

jobs:
  post_to_tumblr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install feedparser requests-oauthlib

      - name: Run Tumblr bot
        env:
          TUMBLR_CONSUMER_KEY: ${{ secrets.TUMBLR_CONSUMER_KEY }}
          TUMBLR_CONSUMER_SECRET: ${{ secrets.TUMBLR_CONSUMER_SECRET }}
          TUMBLR_OAUTH_TOKEN: ${{ secrets.TUMBLR_OAUTH_TOKEN }}
          TUMBLR_OAUTH_TOKEN_SECRET: ${{ secrets.TUMBLR_OAUTH_TOKEN_SECRET }}
        run: python scripts/tumblr_bot.py
